package persistencia;
// Generated 11-08-2018 03:37:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalleplanillas generated by hbm2java
 */
public class Detalleplanillas  implements java.io.Serializable {


     private Integer idDetalle;
     private Empleados empleados;
     private Planillas planillas;
     private BigDecimal salarioBase;
     private BigDecimal bono;
     private BigDecimal isss;
     private BigDecimal renta;
     private BigDecimal afp;
     private BigDecimal salarioNeto;
     private BigDecimal aguinaldo;
     private BigDecimal horasExtras;

    public Detalleplanillas() {
    }

    public Detalleplanillas(Empleados empleados, Planillas planillas, BigDecimal salarioBase, BigDecimal bono, BigDecimal isss, BigDecimal renta, BigDecimal afp, BigDecimal salarioNeto, BigDecimal aguinaldo, BigDecimal horasExtras) {
       this.empleados = empleados;
       this.planillas = planillas;
       this.salarioBase = salarioBase;
       this.bono = bono;
       this.isss = isss;
       this.renta = renta;
       this.afp = afp;
       this.salarioNeto = salarioNeto;
       this.aguinaldo = aguinaldo;
       this.horasExtras = horasExtras;
    }
   
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Planillas getPlanillas() {
        return this.planillas;
    }
    
    public void setPlanillas(Planillas planillas) {
        this.planillas = planillas;
    }
    public BigDecimal getSalarioBase() {
        return this.salarioBase;
    }
    
    public void setSalarioBase(BigDecimal salarioBase) {
        this.salarioBase = salarioBase;
    }
    public BigDecimal getBono() {
        return this.bono;
    }
    
    public void setBono(BigDecimal bono) {
        this.bono = bono;
    }
    public BigDecimal getIsss() {
        return this.isss;
    }
    
    public void setIsss(BigDecimal isss) {
        this.isss = isss;
    }
    public BigDecimal getRenta() {
        return this.renta;
    }
    
    public void setRenta(BigDecimal renta) {
        this.renta = renta;
    }
    public BigDecimal getAfp() {
        return this.afp;
    }
    
    public void setAfp(BigDecimal afp) {
        this.afp = afp;
    }
    public BigDecimal getSalarioNeto() {
        return this.salarioNeto;
    }
    
    public void setSalarioNeto(BigDecimal salarioNeto) {
        this.salarioNeto = salarioNeto;
    }
    public BigDecimal getAguinaldo() {
        return this.aguinaldo;
    }
    
    public void setAguinaldo(BigDecimal aguinaldo) {
        this.aguinaldo = aguinaldo;
    }
    public BigDecimal getHorasExtras() {
        return this.horasExtras;
    }
    
    public void setHorasExtras(BigDecimal horasExtras) {
        this.horasExtras = horasExtras;
    }




}


