package persistencia;
// Generated 11-08-2018 03:37:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idempleado;
     private Sucursales sucursales;
     private String estado;
     private String codigoEmpleado;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefono;
     private String email;
     private Date fechaNacimiento;
     private String cargo;
     private BigDecimal salario;
     private Set detalleplanillases = new HashSet(0);

    public Empleados() {
    }

    public Empleados(Sucursales sucursales, String estado, String codigoEmpleado, String nombres, String apellidos, String direccion, String telefono, String email, Date fechaNacimiento, String cargo, BigDecimal salario, Set detalleplanillases) {
       this.sucursales = sucursales;
       this.estado = estado;
       this.codigoEmpleado = codigoEmpleado;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.fechaNacimiento = fechaNacimiento;
       this.cargo = cargo;
       this.salario = salario;
       this.detalleplanillases = detalleplanillases;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(String codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public Set getDetalleplanillases() {
        return this.detalleplanillases;
    }
    
    public void setDetalleplanillases(Set detalleplanillases) {
        this.detalleplanillases = detalleplanillases;
    }




}


