package persistencia;
// Generated 11-08-2018 03:37:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer idempresa;
     private String nombre;
     private String nit;
     private String direccion;
     private String telefono;
     private String email;
     private Set sucursaleses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Empresas() {
    }

    public Empresas(String nombre, String nit, String direccion, String telefono, String email, Set sucursaleses, Set usuarioses) {
       this.nombre = nombre;
       this.nit = nit;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.sucursaleses = sucursaleses;
       this.usuarioses = usuarioses;
    }
   
    public Integer getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(Integer idempresa) {
        this.idempresa = idempresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


