package persistencia;
// Generated 11-08-2018 03:37:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Planillas generated by hbm2java
 */
public class Planillas  implements java.io.Serializable {


     private Integer idplanillas;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Set detalleplanillases = new HashSet(0);

    public Planillas() {
    }

    public Planillas(Date fechaInicio, Date fechaFin, String estado, Set detalleplanillases) {
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.detalleplanillases = detalleplanillases;
    }
   
    public Integer getIdplanillas() {
        return this.idplanillas;
    }
    
    public void setIdplanillas(Integer idplanillas) {
        this.idplanillas = idplanillas;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetalleplanillases() {
        return this.detalleplanillases;
    }
    
    public void setDetalleplanillases(Set detalleplanillases) {
        this.detalleplanillases = detalleplanillases;
    }




}


